import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

import { useGLTF, useAnimations } from '@react-three/drei'
import skaterScene from "../assets/skater_with_animation.glb";
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
// License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
// Source: https://sketchfab.com/3d-models/skater-with-animation-8e2e5783b3e14cce858a023f4ee7c567
// Title: Skater with animation
// */

const Skater = ({isRotating, ...props}) => {
  const skaterRef = useRef()
  const { nodes, materials, animations } = useGLTF(skaterScene)
  const { actions } = useAnimations(animations, skaterRef)
  return (
    <group ref={skaterRef} name="Sketchfab_Scene" {...props}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.75}>
          <group name="Root">
            <group name="Deck" position={[0.05, -0.108, -0.017]}>
              <mesh
                name="Deck_0"
                castShadow
                receiveShadow
                geometry={nodes.Deck_0.geometry}
                material={materials.deck}
              />
              <group
                name="Empty001"
                position={[-0.001, 0.312, -0.094]}
                rotation={[-0.314, 0, 0]}
                scale={0.298}>
                <group name="wheel_back_right" position={[-0.339, 0, 0.005]} scale={3.352}>
                  <mesh
                    name="wheel_back_right_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_back_right_0.geometry}
                    material={materials.wheel}
                  />
                </group>
                <group name="wheel_back_left" position={[0.343, 0.001, 0.005]} scale={3.352}>
                  <mesh
                    name="wheel_back_left_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_back_left_0.geometry}
                    material={materials.wheel}
                  />
                </group>
              </group>
              <group
                name="Empty"
                position={[-0.001, -0.305, -0.093]}
                rotation={[-0.314, 0, 0]}
                scale={0.298}>
                <group name="wheel_front_right" position={[-0.338, -0.002, 0.001]} scale={3.352}>
                  <mesh
                    name="wheel_front_right_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_front_right_0.geometry}
                    material={materials.wheel}
                  />
                </group>
                <group name="wheel_front_left" position={[0.344, -0.001, 0.001]} scale={3.352}>
                  <mesh
                    name="wheel_front_left_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_front_left_0.geometry}
                    material={materials.wheel}
                  />
                </group>
              </group>
              <group name="Truck_front" position={[-0.001, -0.289, -0.04]}>
                <mesh
                  name="Truck_front_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Truck_front_0.geometry}
                  material={materials.truck}
                />
              </group>
              <group name="bearing_front_right_1" position={[-0.116, -0.305, -0.093]}>
                <mesh
                  name="bearing_front_right_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_front_right_1_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_front_right_2" position={[-0.087, -0.305, -0.093]}>
                <mesh
                  name="bearing_front_right_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_front_right_2_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_front_left_2" position={[0.086, -0.305, -0.093]}>
                <mesh
                  name="bearing_front_left_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_front_left_2_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_front_left_1" position={[0.115, -0.305, -0.093]}>
                <mesh
                  name="bearing_front_left_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_front_left_1_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_back_right_1" position={[-0.116, 0.312, -0.093]}>
                <mesh
                  name="bearing_back_right_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_back_right_1_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_back_right_2" position={[-0.087, 0.312, -0.093]}>
                <mesh
                  name="bearing_back_right_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_back_right_2_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_back_left_2" position={[0.086, 0.312, -0.093]}>
                <mesh
                  name="bearing_back_left_2_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_back_left_2_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="bearing_back_left_1" position={[0.115, 0.312, -0.093]}>
                <mesh
                  name="bearing_back_left_1_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.bearing_back_left_1_0.geometry}
                  material={materials.Bearing}
                />
              </group>
              <group name="Truck_back" position={[0, 0.296, -0.04]}>
                <mesh
                  name="Truck_back_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Truck_back_0.geometry}
                  material={materials.truck}
                />
              </group>
            </group>
            <group name="human" position={[0, 0, 0.818]}>
              <primitive object={nodes.human_rootJoint} />
              <skinnedMesh
                name="humanmale_casualsuit06_0"
                geometry={nodes.humanmale_casualsuit06_0.geometry}
                material={materials.male_casualsuit06}
                skeleton={nodes.humanmale_casualsuit06_0.skeleton}
              />
              <skinnedMesh
                name="humanshoes02_0"
                geometry={nodes.humanshoes02_0.geometry}
                material={materials.shoes02}
                skeleton={nodes.humanshoes02_0.skeleton}
              />
              <skinnedMesh
                name="humanHighPolyEyes_0"
                geometry={nodes.humanHighPolyEyes_0.geometry}
                material={materials.HighPolyEyes}
                skeleton={nodes.humanHighPolyEyes_0.skeleton}
              />
              <skinnedMesh
                name="humanBody_0"
                geometry={nodes.humanBody_0.geometry}
                material={materials.body}
                skeleton={nodes.humanBody_0.skeleton}
              />
              <group name="humanmale_casualsuit06" />
              <group name="humanshoes02" />
              <group name="humanHighPolyEyes" />
              <group name="humanBody" />
            </group>
          </group>
        </group>
      </group>
    )
}
  // <primitive object={skater.scene} />

useGLTF.preload(skaterScene)

export default Skater;